rootDir = "/Users/windfolgen/Documents/AntiGravity/svbwalkthrough";
asymDir = FileNameJoin[{rootDir, "asym"}];

(* Load config.wl *)
Get[FileNameJoin[{rootDir, "config.wl"}]];

(* Load LiteRed2 and define variables *)
Get["LiteRed2`"];
SetDim[d];
Declare[{l1, l2, l3, l4, p}, Vector, {u}, Number];
SetConstraints[{p}, sp[p, p] = u];

(* Load bases *)
Do[
  Get[FileNameJoin[{asymDir, "Bases", b, b}]];
  Quiet[ExecuteDefinitions[ToExpression[b]]];
, {b, {"asym", "asym3L", "asym2L", "asym1L"}}];

(* Load asymptotic expansion engine *)
Get[FileNameJoin[{asymDir, "asym_new.wl"}]];

(* Load input for threeloophard1 *)
inputPath = FileNameJoin[{rootDir, "runs", "threeloophard1", "input.wl"}];
Block[{integrand, leadingsingularity, ansatz, OrderY},
  Get[inputPath];
  testIntegrand = integrand;
];

Print["Loaded testIntegrand: ", Short[testIntegrand, 5]];

(* Define the 4 coordinate exchange representations *)
case1 = {1, 2, 3, 4};
case2 = {3, 4, 1, 2};
case3 = {2, 1, 4, 3};
case4 = {4, 3, 2, 1};
cases = {case1, case2, case3, case4};

(* Measure term counts generated by RegionExpand for each case *)
Do[
  intCase = testIntegrand /. {x[a__] :> (x[a] /. Thread@Rule[{1, 2, 3, 4}, c])};
  terms = Length[RegionExpand[intCase, {5, 6, 7}, "order" -> 3, "check" -> False][[2]]];
  Print["Case ", c, " generates ", terms, " terms."];
, {c, cases}];

(* Run asymptotic expansions for all 4 cases *)
Do[
  RunAsymExpansion["threeloophard1Test", testIntegrand, c, 3, {5, 6, 7}];
, {c, cases}];

(* Import and verify that all 4 results are mathematically identical *)
Print["\n=== Verifying mathematical equivalence of results ==="];
res1 = Import[FileNameJoin[{asymDir, "checkthreeloophard1Test1234_order3_asyexp.m"}]];
res2 = Import[FileNameJoin[{asymDir, "checkthreeloophard1Test3412_order3_asyexp.m"}]];
res3 = Import[FileNameJoin[{asymDir, "checkthreeloophard1Test2143_order3_asyexp.m"}]];
res4 = Import[FileNameJoin[{asymDir, "checkthreeloophard1Test4321_order3_asyexp.m"}]];

diff2 = res1 - res2 // Expand // Simplify;
diff3 = res1 - res3 // Expand // Simplify;
diff4 = res1 - res4 // Expand // Simplify;

If[diff2 === 0 && diff3 === 0 && diff4 === 0,
  Print["SUCCESS: All 4 coordinate exchange representations are mathematically identical!"],
  Print["WARNING: Results differ!"];
  Print["Diff 1-2: ", Short[diff2, 10]];
  Print["Diff 1-3: ", Short[diff3, 10]];
  Print["Diff 1-4: ", Short[diff4, 10]];
  Exit[1];
];

(* Clean up test files *)
Do[
  permStr = StringJoin[ToString /@ c];
  file = FileNameJoin[{asymDir, "checkthreeloophard1Test" <> permStr <> "_order3_asyexp.m"}];
  If[FileExistsQ[file], DeleteFile[file]];
, {c, cases}];

Print["Cleanup complete. Symmetry test passed successfully!"];
