$HistoryLength = 0;
rootDir = DirectoryName[$InputFileName];
Get["config.wl"];
Get["series_agent/series_agent.wl"];
ansatz = Import["runs/fourloopI41/fourloopI41ansatz.m"];
basisElements = DeleteDuplicates @ Cases[ansatz, _I | _f, {1, Infinity}];
fullBasisSV = Import[FileNameJoin[{$DataDir, $SVTextPrefix <> "e0_uptow8_inuv.txt"}], "String"];
fullBasisSV = ParseListString[fullBasisSV];
svIndices = Function[e, If[# === {}, 0, #[[1,1]]] & @ Position[fullBasisSV, e, {1}]] /@ basisElements;
svIndices = DeleteDuplicates[Select[svIndices, Positive]];
Print["Length svIndices: ", Length[svIndices]];
